"""upgrade db tables

Revision ID: ca534ea05906
Revises: 1466375b65cd
Create Date: 2023-01-04 14:25:11.083260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca534ea05906'
down_revision = '1466375b65cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
